version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:16.0-alpine
    ports:
      - 5432:5432
    volumes:
      - duretrip:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Duretrip@2023

  maildev:
    container_name: maildev
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - 1080:1080
      - 1025:1025

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./init-rabbitmq.sh:/usr/local/bin/init-rabbitmq.sh
    entrypoint: /bin/sh
    command: -c "chmod +x /usr/local/bin/init-rabbitmq.sh && /usr/local/bin/init-rabbitmq.sh"

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6381:6379"
      - "6380:6380"  # Additional port for the second instance
    environment:
      - REDIS_PASSWORD=password
    volumes:
      - ./redis/init-redis.sh:/usr/local/bin/init-redis.sh
      - ./redis/auth_redis.conf:/etc/redis/auth_redis.conf
      - ./redis/jet_redis.conf:/etc/redis/jet_redis.conf
    command: ["bash", "-c", "chmod +x /usr/local/bin/init-redis.sh && /usr/local/bin/init-redis.sh"]

volumes:
  duretrip:
