version: '3.7'

services:
  main:
    container_name: api-gateway
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 7777:7777
    env_file:
      - .env.dev